services:
  postgres:
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - payments-net

  rabbitmq:
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - payments-net

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.142.0
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./dockerfiles/otel-collector/config.yaml:/etc/otelcol-contrib/config.yaml:ro
    ports:
      - "4317:4317"
      - "8889:8889"
    networks:
      - payments-net

  jaeger:
    image: jaegertracing/all-in-one:1.76.0
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686"
    networks:
      - payments-net

  prometheus:
    image: prom/prometheus:v3.5.0
    volumes:
      - ./dockerfiles/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - payments-net

  api:
    env_file:
      - .env
    environment:
      OTEL_ENABLED: "true"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
    ports:
      - "8000:8000"
    depends_on:
      - otel-collector
    networks:
      - payments-net

  publisher:
    env_file:
      - .env
    environment:
      OTEL_ENABLED: "true"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
    depends_on:
      - otel-collector
    networks:
      - payments-net

  consumer:
    env_file:
      - .env
    environment:
      OTEL_ENABLED: "true"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
    depends_on:
      - otel-collector
    networks:
      - payments-net

  webhook-dispatcher:
    env_file:
      - .env
    environment:
      OTEL_ENABLED: "true"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
    depends_on:
      - otel-collector
    networks:
      - payments-net

  migrate:
    env_file:
      - .env
    networks:
      - payments-net

networks:
  payments-net:
