"""add outbox pending index

Revision ID: 557442c8763a
Revises: b567bf1711b3
Create Date: 2026-07-10 23:57:28.093649

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "557442c8763a"
down_revision: Union[str, Sequence[str], None] = "b567bf1711b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_outbox_pending",
        "outbox",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_outbox_pending",
        table_name="outbox",
        postgresql_where=sa.text("status = 'pending'"),
    )
    # ### end Alembic commands ###
