"""Generate OpenAPI specification file from the FastAPI application."""

from pathlib import Path

import yaml

from app.main import app

DOCS_DIR = Path(__file__).resolve().parents[1] / "docs"
OUTPUT_PATH = DOCS_DIR / "openapi.yaml"


def generate_openapi_schema() -> dict:
    """Return the OpenAPI schema generated by FastAPI."""
    return app.openapi()


def write_openapi_yaml(schema: dict, output_path: Path = OUTPUT_PATH) -> None:
    """Write OpenAPI schema to a YAML file.

    Args:
        schema: OpenAPI schema dictionary.
        output_path: Destination file path.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as file:
        yaml.dump(
            schema,
            file,
            sort_keys=False,
            allow_unicode=True,
            default_flow_style=False,
        )


def main() -> None:
    """Generate docs/openapi.yaml from the FastAPI application."""
    schema = generate_openapi_schema()
    write_openapi_yaml(schema)
    print(f"OpenAPI schema written to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
